---
  - apt:
      name: "{{ item.name }}=1:{{ item.version }}*"
      state: "{{ item.state }}"
      update_cache: yes
    with_items: "{{ php_fpm_packages }}"
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    notify: start_php_fpm

  - yum:
      name: "{{ item.name }}=1:{{ item.version }}*"
      state: "{{ item.state }}"
      update_cache: yes
    with_items: "{{ php_fpm_packages }}"
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
    notify: start_php_fpm